{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wonder.payment.sdk",
    "module": "wonderpayment-android",
    "version": "0.7.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "wonderpayment-android-0.7.5.aar",
          "url": "wonderpayment-android-0.7.5.aar",
          "size": 3263162,
          "sha512": "93fe33b361595bc17d5180190bbf14a6eda63ad4a13600b4c04418503ffbae4bc1eb01b3a75b99dbede4ce1e7b14bcb86b29d3ce39f99f9295827a0266e91fa3",
          "sha256": "f531a8b5a66b750b15bec6c4fca0154715739cca353a93767e95b4ae3ccdcc54",
          "sha1": "ed1711aa4c8338608221bec6652cac608308f22d",
          "md5": "25a2b7102dac5ac170081db87563f3bc"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.geyifeng.immersionbar",
          "module": "immersionbar",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.16.0"
          }
        },
        {
          "group": "com.alipay.sdk",
          "module": "alipaysdk-android",
          "version": {
            "requires": "15.8.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "alipaysdk-android",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.tencent.mm.opensdk",
          "module": "wechat-sdk-android",
          "version": {
            "requires": "6.8.24"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.1.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "wonderpayment-android-0.7.5.aar",
          "url": "wonderpayment-android-0.7.5.aar",
          "size": 3263162,
          "sha512": "93fe33b361595bc17d5180190bbf14a6eda63ad4a13600b4c04418503ffbae4bc1eb01b3a75b99dbede4ce1e7b14bcb86b29d3ce39f99f9295827a0266e91fa3",
          "sha256": "f531a8b5a66b750b15bec6c4fca0154715739cca353a93767e95b4ae3ccdcc54",
          "sha1": "ed1711aa4c8338608221bec6652cac608308f22d",
          "md5": "25a2b7102dac5ac170081db87563f3bc"
        }
      ]
    }
  ]
}
