{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wonder.payment.sdk",
    "module": "wonderpayment-android",
    "version": "0.7.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "wonderpayment-android-0.7.17.aar",
          "url": "wonderpayment-android-0.7.17.aar",
          "size": 3374732,
          "sha512": "ac2e9a3d3160b0c9eadabcf11eb535f5fc837cdcf70d81e7546cf474efbb16089dcdb87e307d99515679b3341614995d2703fb853ea4258a8abfe3d97de68775",
          "sha256": "f710fa8df6ca64506560b15fb95825fbbdacc3bd3dc2426f4838adc0a3cf5e98",
          "sha1": "84495484e32b36d682667eedffab1afe12304b3b",
          "md5": "7eae14e569848e95e14c52b8fdda9cf8"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.geyifeng.immersionbar",
          "module": "immersionbar",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.16.0"
          }
        },
        {
          "group": "com.alipay.sdk",
          "module": "alipaysdk-android",
          "version": {
            "requires": "15.8.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "alipaysdk-android",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.tencent.mm.opensdk",
          "module": "wechat-sdk-android",
          "version": {
            "requires": "6.8.24"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.1.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "wonderpayment-android-0.7.17.aar",
          "url": "wonderpayment-android-0.7.17.aar",
          "size": 3374732,
          "sha512": "ac2e9a3d3160b0c9eadabcf11eb535f5fc837cdcf70d81e7546cf474efbb16089dcdb87e307d99515679b3341614995d2703fb853ea4258a8abfe3d97de68775",
          "sha256": "f710fa8df6ca64506560b15fb95825fbbdacc3bd3dc2426f4838adc0a3cf5e98",
          "sha1": "84495484e32b36d682667eedffab1afe12304b3b",
          "md5": "7eae14e569848e95e14c52b8fdda9cf8"
        }
      ]
    }
  ]
}
