{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wonder.payment.sdk",
    "module": "wonderpayment-android",
    "version": "0.7.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "wonderpayment-android-0.7.15.aar",
          "url": "wonderpayment-android-0.7.15.aar",
          "size": 3374807,
          "sha512": "2519189cd848e498dcb447268ee9e5c473d72cc40aac8bcb3f8d0ce64b0a55cba4da02f9f667e5c119930041a2d8789f52e76e38ffbb007f31f9e8433616c997",
          "sha256": "bf988370f6a4cfdd0c44379707af34591b43ab737584aa61b63bc4a006ce7bc7",
          "sha1": "762a8e9f3d29ff44a29edc7b2c6c125557e65363",
          "md5": "e6ee67f281407aadfb9c2b6d4a7507f0"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.geyifeng.immersionbar",
          "module": "immersionbar",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.16.0"
          }
        },
        {
          "group": "com.alipay.sdk",
          "module": "alipaysdk-android",
          "version": {
            "requires": "15.8.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "alipaysdk-android",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.tencent.mm.opensdk",
          "module": "wechat-sdk-android",
          "version": {
            "requires": "6.8.24"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.1.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "wonderpayment-android-0.7.15.aar",
          "url": "wonderpayment-android-0.7.15.aar",
          "size": 3374807,
          "sha512": "2519189cd848e498dcb447268ee9e5c473d72cc40aac8bcb3f8d0ce64b0a55cba4da02f9f667e5c119930041a2d8789f52e76e38ffbb007f31f9e8433616c997",
          "sha256": "bf988370f6a4cfdd0c44379707af34591b43ab737584aa61b63bc4a006ce7bc7",
          "sha1": "762a8e9f3d29ff44a29edc7b2c6c125557e65363",
          "md5": "e6ee67f281407aadfb9c2b6d4a7507f0"
        }
      ]
    }
  ]
}
