{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wonder.payment.sdk",
    "module": "wonderpayment-android",
    "version": "0.8.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "wonderpayment-android-0.8.8.aar",
          "url": "wonderpayment-android-0.8.8.aar",
          "size": 1402405,
          "sha512": "d1530271ab5f4df035766c22d5606daf866cf33c6b1bf5718ca8b9487046dd8b87eb0fb4cf7da01ae7b95c637fa9ad6b53c5a055cf42d130e74b6c43701e388f",
          "sha256": "eebbb2f7e1a2d7d38e754660fa7933000659d90219c3b25d643c926fa6899aa0",
          "sha1": "ffa511352ed71feeec03f416f71a6192e167a0bd",
          "md5": "c3f25da0e1d5f2e080ccbe8b4e47303c"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.geyifeng.immersionbar",
          "module": "immersionbar",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.16.0"
          }
        },
        {
          "group": "com.alipay.sdk",
          "module": "alipaysdk-android",
          "version": {
            "requires": "15.8.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "alipaysdk-android",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.tencent.mm.opensdk",
          "module": "wechat-sdk-android",
          "version": {
            "requires": "6.8.24"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.1.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "wonderpayment-android-0.8.8.aar",
          "url": "wonderpayment-android-0.8.8.aar",
          "size": 1402405,
          "sha512": "d1530271ab5f4df035766c22d5606daf866cf33c6b1bf5718ca8b9487046dd8b87eb0fb4cf7da01ae7b95c637fa9ad6b53c5a055cf42d130e74b6c43701e388f",
          "sha256": "eebbb2f7e1a2d7d38e754660fa7933000659d90219c3b25d643c926fa6899aa0",
          "sha1": "ffa511352ed71feeec03f416f71a6192e167a0bd",
          "md5": "c3f25da0e1d5f2e080ccbe8b4e47303c"
        }
      ]
    }
  ]
}
