{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wonder.payment.sdk",
    "module": "wonderpayment-android",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "wonderpayment-android-0.1.0.aar",
          "url": "wonderpayment-android-0.1.0.aar",
          "size": 1634213,
          "sha512": "ad5906bb49aa91f855f445a3f12c4cb0fa8cf8ff4767772e8982824e40259bbd44052f43f6da6761b3de1553422b5c0859e51c9db88f257445b054749f707b74",
          "sha256": "bf4fe371a7b91a784879c618207b5753977b38f62eaa59f36db457614967fa16",
          "sha1": "0efc441b3f7eb11b3da8baf65c2a03b50b589e66",
          "md5": "89c67d3fcc9d8e2330a5c40f28663120"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.geyifeng.immersionbar",
          "module": "immersionbar",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.alipay.sdk",
          "module": "alipaysdk-android",
          "version": {
            "requires": "15.8.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "alipaysdk-android",
              "type": "aar",
              "extension": "aar"
            }
          }
        },
        {
          "group": "com.tencent.mm.opensdk",
          "module": "wechat-sdk-android",
          "version": {
            "requires": "6.8.24"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wallet",
          "version": {
            "requires": "19.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "wonderpayment-android-0.1.0.aar",
          "url": "wonderpayment-android-0.1.0.aar",
          "size": 1634213,
          "sha512": "ad5906bb49aa91f855f445a3f12c4cb0fa8cf8ff4767772e8982824e40259bbd44052f43f6da6761b3de1553422b5c0859e51c9db88f257445b054749f707b74",
          "sha256": "bf4fe371a7b91a784879c618207b5753977b38f62eaa59f36db457614967fa16",
          "sha1": "0efc441b3f7eb11b3da8baf65c2a03b50b589e66",
          "md5": "89c67d3fcc9d8e2330a5c40f28663120"
        }
      ]
    }
  ]
}
